version: '3'
services:
  phpfpm:
    container_name: phpfpm
    image: nanoninja/php-fpm:7.4.0
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html"